name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  playwright:
    name: Playwright
    if: github.actor != 'shopify[bot]'
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler: 'latest'
    - name: Install Shopify CLI
      run: npm install -g @shopify/cli @shopify/theme
    - name: Run Playwright tests
      env:
        SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_FLAG_STORE }}
        SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
        SHOPIFY_CLI_TTY: 0
        SHOPIFY_ONLINE_STORE_PASSWORD: ${{ secrets.SHOPIFY_ONLINE_STORE_PASSWORD }}
      run: npx playwright test --update-snapshots
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: .playwright/report/
        retention-days: 7
